# Generated by Django 4.1.7 on 2023-03-10 21:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_product_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.CharField(choices=[('1', 'خیلی بد'), ('2', 'بد'), ('3', 'معمولی'), ('4', 'خوب'), ('5', 'خیلی خوب')], max_length=10, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
