# Generated by Django 4.1.7 on 2023-04-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_short_description_alter_comment_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
